[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.setuptools",
  "python310Packages.pip",
  "python310Packages.distutils",
  "libGL",
  "libGLU",
  "mesa",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libXi"
] 